platform :ios, "8.0"

pod 'AFNetworking', '~> 3.0.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SVProgressHUD-0.8.1', '~> 0.8'
pod 'SDWebImage', '~> 3.7.5'
pod 'DACircularProgress'
pod 'pop'

xcodeproj '/Volumes/贼贼Believe/百思不得姐/BaiSi/百思不得姐/百思不得姐.xcodeproj'